<a href="https://colab.research.google.com/github/yoonjihwan402/medical-data/blob/main/04_statistical_significance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 가설 검증
## p-value 계산
- 동전을 10번 던졌을 때 8번 앞면이 나온 것을 보고 이 동전은 앞면이 뒷면보다 자주 나온다라는 대립 가설을 세움
- 귀무가설 : 위 사실은 우연이고 가끔씩 그런 결과가 나온다. 이 동전은 앞면이 나올 확률이 ½인 보통 동전이다.
- 10번씩 1000회 반복 시 10번 중 8번 앞면이 나온 회수

In [1]:
import numpy as np
np.random.seed(1000)

In [4]:
# 이항분포
binomial_example = np.random.binomial(10, 0.5, 10) # 1~10까지 0.5 확률의 10번 시행 이항 분포
binomial_example

array([2, 8, 4, 6, 4, 2, 7, 6, 6, 5])

In [5]:
coin_test = np.random.binomial(10, 0.5, 1000) # 이항 분포
coin_test

array([ 7,  7,  1,  3,  4,  3,  6,  5,  7,  4,  5,  2,  6,  5,  3,  7,  7,
        3,  2,  5,  5,  4,  6,  4,  5,  5,  5,  3,  4,  3,  4,  4,  5,  5,
        5,  4,  5,  7,  7,  3,  4,  5,  6,  6,  5,  5,  6,  5,  7,  3,  4,
        8,  6,  7,  4,  6,  4,  5,  4,  5,  6,  4,  5,  5,  7,  6,  6,  4,
        5,  2,  3,  7,  3,  7,  6,  5,  6,  3,  6,  6,  5,  5,  5,  5,  6,
        4,  3,  8,  5,  6,  6,  5,  3,  4,  5,  5,  6,  4,  5,  7,  6,  3,
        3,  6,  5,  8,  6,  6,  4,  5,  6,  1,  5,  5,  4,  4,  7,  2,  4,
        4,  8,  2,  5,  4,  6,  6,  6,  7,  8,  3,  3,  2,  7,  8,  4,  3,
        3,  7,  5,  4,  6,  6,  5,  2,  4,  7,  3,  3,  6,  3,  3,  4,  4,
        4,  6,  4,  3,  3,  4,  4,  7,  5,  4,  9,  5,  7,  4,  4,  8,  3,
        7,  8,  4,  7,  7, 10,  3,  5,  6,  6,  7,  2,  8,  3,  2,  8,  4,
        7,  2,  2,  3,  6,  4,  5,  8,  4,  4,  5,  4,  5,  5,  4,  2,  6,
        7,  4,  5,  3,  6,  4,  3,  3,  4,  6,  5,  6,  3,  4,  6,  1,  4,
        7,  6,  4,  6,  3

In [6]:
result = sum(1 for x in coin_test if x >= 8) # 8 이상인 회수 카운트
result

59

In [7]:
p_value = result / 1000
p_value

0.059

- 이 결과는 유의하다 않다

## CDF를 이용한 p-value 구하기

In [8]:
from scipy.stats import binom
n, p = 10, 0.5
rv = binom(n, p) # rv : random variable
result = rv.cdf(7)
p_value_cdf = 1 - result
p_value_cdf

np.float64(0.0546875)

# 카이제곱 검정

In [9]:
from scipy.stats import chi2_contingency as chi2
observation = ([100,400], [100,1400]) # tuple
chi2_result, p, df, expectation = chi2(observation, correction=False)
print(f"카이제곱 검정 통계량 : {chi2_result}, p-value : {p}, df : {df}")
print("expectation")
print(expectation)

카이제곱 검정 통계량 : 74.07407407407408, p-value : 7.524003528881426e-18, df : 1
expectation
[[  50.  450.]
 [ 150. 1350.]]


# t-test
- equal_val True : Student's t-test, False : Welch's t-test

In [10]:
from scipy import stats
X_bar_1, s1, n1 = 100, 20, 100
X_bar_2, s2, n2 = 80, 30, 300
students_tt = stats.ttest_ind_from_stats(X_bar_1,s1,n1,X_bar_2,s2,n2,equal_var=True)
welchs_tt = stats.ttest_ind_from_stats(X_bar_1,s1,n1,X_bar_2,s2,n2,equal_var=False)
print(students_tt)
print(welchs_tt)

Ttest_indResult(statistic=np.float64(6.2191903391234815), pvalue=np.float64(1.2650376446939409e-09))
Ttest_indResult(statistic=np.float64(7.559289460184544), pvalue=np.float64(7.260967576525536e-13))
